# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20171102_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(auto_now_add=True),
        ),
    ]
